
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int BC = 13;
  public static final int PIPE = 18;
  public static final int INT = 20;
  public static final int CM = 10;
  public static final int S = 11;
  public static final int RO = 14;
  public static final int NAME = 21;
  public static final int M = 9;
  public static final int MS = 8;
  public static final int RC = 15;
  public static final int EOF = 0;
  public static final int C = 16;
  public static final int SEP = 5;
  public static final int ARROW = 19;
  public static final int error = 1;
  public static final int EQ = 17;
  public static final int BO = 12;
  public static final int TK3 = 4;
  public static final int PRINT_M_M = 6;
  public static final int TK2 = 3;
  public static final int TK1 = 2;
  public static final int PART = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK1",
  "TK2",
  "TK3",
  "SEP",
  "PRINT_M_M",
  "PART",
  "MS",
  "M",
  "CM",
  "S",
  "BO",
  "BC",
  "RO",
  "RC",
  "C",
  "EQ",
  "PIPE",
  "ARROW",
  "INT",
  "NAME"
  };
}

