
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

import java_cup.runtime.*;
import cup.example.Lexer;
import java.io.IOException;
import java.io.File;
import java.io.FileInputStream;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20141204 (SVN rev 60) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\051\000\002\002\005\000\002\002\004\000\002\002" +
    "\004\000\002\003\005\000\002\003\005\000\002\003\005" +
    "\000\002\003\003\000\002\003\003\000\002\003\003\000" +
    "\002\003\003\000\002\003\003\000\002\003\003\000\002" +
    "\003\003\000\002\003\003\000\002\003\003\000\002\003" +
    "\003\000\002\003\003\000\002\003\003\000\002\003\003" +
    "\000\002\003\003\000\002\003\003\000\002\003\003\000" +
    "\002\003\003\000\002\003\003\000\002\003\003\000\002" +
    "\003\003\000\002\003\003\000\002\003\003\000\002\003" +
    "\003\000\002\003\003\000\002\003\003\000\002\003\003" +
    "\000\002\003\003\000\002\003\003\000\002\003\003\000" +
    "\002\003\003\000\002\003\003\000\002\003\003\000\002" +
    "\003\004\000\002\003\005\000\002\003\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\063\000\110\006\015\011\014\013\004\014\021\015" +
    "\045\016\005\017\022\020\012\021\006\022\024\023\032" +
    "\024\007\025\026\026\047\027\030\030\044\031\027\032" +
    "\013\033\033\034\017\035\011\036\031\037\037\040\025" +
    "\041\041\042\023\043\046\044\016\045\036\046\010\047" +
    "\043\050\035\051\020\052\040\053\034\001\002\000\014" +
    "\004\ufffb\005\ufffb\006\ufffb\010\ufffb\012\ufffb\001\002\000" +
    "\014\004\ufff8\005\ufff8\006\ufff8\010\ufff8\012\ufff8\001\002" +
    "\000\014\004\ufff5\005\ufff5\006\ufff5\010\ufff5\012\ufff5\001" +
    "\002\000\014\004\ufff2\005\ufff2\006\ufff2\010\ufff2\012\ufff2" +
    "\001\002\000\014\004\uffe0\005\uffe0\006\uffe0\010\uffe0\012" +
    "\uffe0\001\002\000\014\004\uffe9\005\uffe9\006\uffe9\010\uffe9" +
    "\012\uffe9\001\002\000\014\004\ufff6\005\ufff6\006\ufff6\010" +
    "\ufff6\012\ufff6\001\002\000\014\004\uffec\005\uffec\006\uffec" +
    "\010\uffec\012\uffec\001\002\000\110\006\015\011\014\013" +
    "\004\014\021\015\045\016\005\017\022\020\012\021\006" +
    "\022\024\023\032\024\007\025\026\026\047\027\030\030" +
    "\044\031\027\032\013\033\033\034\017\035\011\036\031" +
    "\037\037\040\025\041\041\042\023\043\046\044\016\045" +
    "\036\046\010\047\043\050\035\051\020\052\040\053\034" +
    "\001\002\000\110\006\015\011\014\013\004\014\021\015" +
    "\045\016\005\017\022\020\012\021\006\022\024\023\032" +
    "\024\007\025\026\026\047\027\030\030\044\031\027\032" +
    "\013\033\033\034\017\035\011\036\031\037\037\040\025" +
    "\041\041\042\023\043\046\044\016\045\036\046\010\047" +
    "\043\050\035\051\020\052\040\053\034\001\002\000\014" +
    "\004\uffe2\005\uffe2\006\uffe2\010\uffe2\012\uffe2\001\002\000" +
    "\014\004\uffea\005\uffea\006\uffea\010\uffea\012\uffea\001\002" +
    "\000\014\004\uffdd\005\uffdd\006\uffdd\010\uffdd\012\uffdd\001" +
    "\002\000\014\004\ufffa\005\ufffa\006\ufffa\010\ufffa\012\ufffa" +
    "\001\002\000\014\004\ufff7\005\ufff7\006\ufff7\010\ufff7\012" +
    "\ufff7\001\002\000\014\004\uffe4\005\uffe4\006\uffe4\010\uffe4" +
    "\012\uffe4\001\002\000\014\004\ufff4\005\ufff4\006\ufff4\010" +
    "\ufff4\012\ufff4\001\002\000\014\004\uffe6\005\uffe6\006\uffe6" +
    "\010\uffe6\012\uffe6\001\002\000\014\004\ufff1\005\ufff1\006" +
    "\ufff1\010\ufff1\012\ufff1\001\002\000\014\004\uffed\005\uffed" +
    "\006\uffed\010\uffed\012\uffed\001\002\000\014\004\uffef\005" +
    "\uffef\006\uffef\010\uffef\012\uffef\001\002\000\014\004\uffe8" +
    "\005\uffe8\006\uffe8\010\uffe8\012\uffe8\001\002\000\014\004" +
    "\ufff3\005\ufff3\006\ufff3\010\ufff3\012\ufff3\001\002\000\014" +
    "\004\uffeb\005\uffeb\006\uffeb\010\uffeb\012\uffeb\001\002\000" +
    "\014\004\uffd9\005\uffd9\006\uffd9\010\uffd9\012\uffd9\001\002" +
    "\000\014\004\uffde\005\uffde\006\uffde\010\uffde\012\uffde\001" +
    "\002\000\014\004\uffe1\005\uffe1\006\uffe1\010\uffe1\012\uffe1" +
    "\001\002\000\014\004\uffe7\005\uffe7\006\uffe7\010\uffe7\012" +
    "\uffe7\001\002\000\014\004\uffdc\005\uffdc\006\uffdc\010\uffdc" +
    "\012\uffdc\001\002\000\014\004\uffe5\005\uffe5\006\uffe5\010" +
    "\uffe5\012\uffe5\001\002\000\012\004\062\005\053\006\055" +
    "\010\056\001\002\000\014\004\uffdf\005\uffdf\006\uffdf\010" +
    "\uffdf\012\uffdf\001\002\000\014\004\uffee\005\uffee\006\uffee" +
    "\010\uffee\012\uffee\001\002\000\014\004\ufff9\005\ufff9\006" +
    "\ufff9\010\ufff9\012\ufff9\001\002\000\014\004\uffe3\005\uffe3" +
    "\006\uffe3\010\uffe3\012\uffe3\001\002\000\014\004\ufff0\005" +
    "\ufff0\006\ufff0\010\ufff0\012\ufff0\001\002\000\112\002\051" +
    "\006\015\011\014\013\004\014\021\015\045\016\005\017" +
    "\022\020\012\021\006\022\024\023\032\024\007\025\026" +
    "\026\047\027\030\030\044\031\027\032\013\033\033\034" +
    "\017\035\011\036\031\037\037\040\025\041\041\042\023" +
    "\043\046\044\016\045\036\046\010\047\043\050\035\051" +
    "\020\052\040\053\034\001\002\000\004\002\000\001\002" +
    "\000\012\004\054\005\053\006\055\010\056\001\002\000" +
    "\110\006\015\011\014\013\004\014\021\015\045\016\005" +
    "\017\022\020\012\021\006\022\024\023\032\024\007\025" +
    "\026\026\047\027\030\030\044\031\027\032\013\033\033" +
    "\034\017\035\011\036\031\037\037\040\025\041\041\042" +
    "\023\043\046\044\016\045\036\046\010\047\043\050\035" +
    "\051\020\052\040\053\034\001\002\000\112\002\001\006" +
    "\001\011\001\013\001\014\001\015\001\016\001\017\001" +
    "\020\001\021\001\022\001\023\001\024\001\025\001\026" +
    "\001\027\001\030\001\031\001\032\001\033\001\034\001" +
    "\035\001\036\001\037\001\040\001\041\001\042\001\043" +
    "\001\044\001\045\001\046\001\047\001\050\001\051\001" +
    "\052\001\053\001\001\002\000\110\006\015\011\014\013" +
    "\004\014\021\015\045\016\005\017\022\020\012\021\006" +
    "\022\024\023\032\024\007\025\026\026\047\027\030\030" +
    "\044\031\027\032\013\033\033\034\017\035\011\036\031" +
    "\037\037\040\025\041\041\042\023\043\046\044\016\045" +
    "\036\046\010\047\043\050\035\051\020\052\040\053\034" +
    "\001\002\000\110\006\015\011\014\013\004\014\021\015" +
    "\045\016\005\017\022\020\012\021\006\022\024\023\032" +
    "\024\007\025\026\026\047\027\030\030\044\031\027\032" +
    "\013\033\033\034\017\035\011\036\031\037\037\040\025" +
    "\041\041\042\023\043\046\044\016\045\036\046\010\047" +
    "\043\050\035\051\020\052\040\053\034\001\002\000\014" +
    "\004\ufffc\005\ufffc\006\ufffc\010\ufffc\012\ufffc\001\002\000" +
    "\014\004\ufffd\005\ufffd\006\ufffd\010\056\012\ufffd\001\002" +
    "\000\014\004\ufffe\005\ufffe\006\ufffe\010\056\012\ufffe\001" +
    "\002\000\112\002\uffff\006\uffff\011\uffff\013\uffff\014\uffff" +
    "\015\uffff\016\uffff\017\uffff\020\uffff\021\uffff\022\uffff\023" +
    "\uffff\024\uffff\025\uffff\026\uffff\027\uffff\030\uffff\031\uffff" +
    "\032\uffff\033\uffff\034\uffff\035\uffff\036\uffff\037\uffff\040" +
    "\uffff\041\uffff\042\uffff\043\uffff\044\uffff\045\uffff\046\uffff" +
    "\047\uffff\050\uffff\051\uffff\052\uffff\053\uffff\001\002\000" +
    "\014\004\uffdb\005\uffdb\006\uffdb\010\uffdb\012\uffdb\001\002" +
    "\000\012\005\053\006\055\010\056\012\065\001\002\000" +
    "\014\004\uffda\005\uffda\006\uffda\010\uffda\012\uffda\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\063\000\006\002\047\003\041\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\003\063\001\001\000\004\003\062" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\003\051\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\003\060\001\001\000\002\001\001" +
    "\000\004\003\057\001\001\000\004\003\056\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {
//@@CUPDBG1

  ComplexSymbolFactory f = new ComplexSymbolFactory();
  symbolFactory = f;
  File file = new File("input.txt");
  FileInputStream fis = null;
  try {
    fis = new FileInputStream(file);
  } catch (IOException e) {
    e.printStackTrace();
  } 
  lexer = new Lexer(f,fis);

    }

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
//@@CUPDBG2
 return lexer.next_token(); 
    }

//@@CUPDBG0

  protected Lexer lexer;


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // expr_list ::= expr_list expr SEMI 
            {
              Object RESULT =null;
		Location exleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).xleft;
		Location exright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).xright;
		Integer e = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		//@@CUPDBG3
  if (e == 101) System.out.print("*0.01"); 
												else if (e == 102) System.out.print("*0.1"); 
												else if (e == 103) System.out.print("*1"); 
												else if (e == 104) System.out.print("*10"); 
												else if (e == 105) System.out.print("*100"); 
												else if (e == 106) System.out.print("*1k"); 
												else if (e == 107) System.out.print("*10k"); 
												else if (e == 108) System.out.print("*100k"); 
												else if (e == 109) System.out.print("*1M"); 
												else if (e == 110) System.out.print("*10M"); 
												else if (e == 1000) System.out.println("+-10%"); 
												else if (e == 1500) System.out.println("+-5%"); 
												else System.out.print(e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_list",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= expr_list EOF 
            {
              Object RESULT =null;
		Location start_valxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).xleft;
		Location start_valxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).xright;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // expr_list ::= expr SEMI 
            {
              Object RESULT =null;
		Location exleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).xleft;
		Location exright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).xright;
		Integer e = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		//@@CUPDBG4
  if (e == 101) System.out.print("*0.01"); 
												else if (e == 102) System.out.print("*0.1"); 
												else if (e == 103) System.out.print("*1"); 
												else if (e == 104) System.out.print("*10"); 
												else if (e == 105) System.out.print("*100"); 
												else if (e == 106) System.out.print("*1k"); 
												else if (e == 107) System.out.print("*10k"); 
												else if (e == 108) System.out.print("*100k"); 
												else if (e == 109) System.out.print("*1M"); 
												else if (e == 110) System.out.print("*10M"); 
												else if (e == 1000) System.out.println("± 10%"); 
												else if (e == 1500) System.out.println("± 5%"); 
												else System.out.print(e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_list",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // expr ::= expr PLUS expr 
            {
              Integer RESULT =null;
		Location e1xleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).xleft;
		Location e1xright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).xright;
		Integer e1 = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		Location e2xleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.peek()).xleft;
		Location e2xright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.peek()).xright;
		Integer e2 = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		//@@CUPDBG5
 RESULT = e1+e2;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // expr ::= expr MINUS expr 
            {
              Integer RESULT =null;
		Location e1xleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).xleft;
		Location e1xright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).xright;
		Integer e1 = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		Location e2xleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.peek()).xleft;
		Location e2xright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.peek()).xright;
		Integer e2 = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		//@@CUPDBG6
 RESULT = e1-e2;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // expr ::= expr TIMES expr 
            {
              Integer RESULT =null;
		Location e1xleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).xleft;
		Location e1xright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).xright;
		Integer e1 = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		Location e2xleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.peek()).xleft;
		Location e2xright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.peek()).xright;
		Integer e2 = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		//@@CUPDBG7
 RESULT = e1*e2;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // expr ::= BLACKONE 
            {
              Integer RESULT =null;
		//@@CUPDBG8
 RESULT = 0;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // expr ::= BLACKTWO 
            {
              Integer RESULT =null;
		//@@CUPDBG9
 RESULT = 0;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // expr ::= BLACKTHREE 
            {
              Integer RESULT =null;
		//@@CUPDBG10
 RESULT = 103;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expr ::= BROWNONE 
            {
              Integer RESULT =null;
		//@@CUPDBG11
 RESULT = 1;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // expr ::= BROWNTWO 
            {
              Integer RESULT =null;
		//@@CUPDBG12
 RESULT = 1;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // expr ::= BROWNTHREE 
            {
              Integer RESULT =null;
		//@@CUPDBG13
 RESULT = 104;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // expr ::= REDONE 
            {
              Integer RESULT =null;
		//@@CUPDBG14
 RESULT = 2;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // expr ::= REDTWO 
            {
              Integer RESULT =null;
		//@@CUPDBG15
 RESULT = 2;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // expr ::= REDTHREE 
            {
              Integer RESULT =null;
		//@@CUPDBG16
 RESULT = 105;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expr ::= ORANGEONE 
            {
              Integer RESULT =null;
		//@@CUPDBG17
 RESULT = 3;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // expr ::= ORANGETWO 
            {
              Integer RESULT =null;
		//@@CUPDBG18
 RESULT = 3;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // expr ::= ORANGETHREE 
            {
              Integer RESULT =null;
		//@@CUPDBG19
 RESULT = 106;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expr ::= YELLOWONE 
            {
              Integer RESULT =null;
		//@@CUPDBG20
 RESULT = 4;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expr ::= YELLOWTWO 
            {
              Integer RESULT =null;
		//@@CUPDBG21
 RESULT = 4;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expr ::= YELLOWTHREE 
            {
              Integer RESULT =null;
		//@@CUPDBG22
 RESULT = 107;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expr ::= GREENONE 
            {
              Integer RESULT =null;
		//@@CUPDBG23
 RESULT = 5;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expr ::= GREENTWO 
            {
              Integer RESULT =null;
		//@@CUPDBG24
 RESULT = 5;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expr ::= GREENTHREE 
            {
              Integer RESULT =null;
		//@@CUPDBG25
 RESULT = 108;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expr ::= BLUEONE 
            {
              Integer RESULT =null;
		//@@CUPDBG26
 RESULT = 6;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expr ::= BLUETWO 
            {
              Integer RESULT =null;
		//@@CUPDBG27
 RESULT = 6;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expr ::= BLUETHREE 
            {
              Integer RESULT =null;
		//@@CUPDBG28
 RESULT = 109;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expr ::= PURPLEONE 
            {
              Integer RESULT =null;
		//@@CUPDBG29
 RESULT = 7;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expr ::= PURPLETWO 
            {
              Integer RESULT =null;
		//@@CUPDBG30
 RESULT = 7;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expr ::= PURPLETHREE 
            {
              Integer RESULT =null;
		//@@CUPDBG31
 RESULT = 110;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expr ::= GRAYONE 
            {
              Integer RESULT =null;
		//@@CUPDBG32
 RESULT = 8;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expr ::= GRAYTWO 
            {
              Integer RESULT =null;
		//@@CUPDBG33
 RESULT = 8;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expr ::= WHITEONE 
            {
              Integer RESULT =null;
		//@@CUPDBG34
 RESULT = 9;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expr ::= WHITETWO 
            {
              Integer RESULT =null;
		//@@CUPDBG35
 RESULT = 9;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expr ::= SILVERTHREE 
            {
              Integer RESULT =null;
		//@@CUPDBG36
 RESULT = 101;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expr ::= SILVERFOUR 
            {
              Integer RESULT =null;
		//@@CUPDBG37
 RESULT = 1000;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expr ::= GOLDENTHREE 
            {
              Integer RESULT =null;
		//@@CUPDBG38
 RESULT = 102;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expr ::= GOLDENFOUR 
            {
              Integer RESULT =null;
		//@@CUPDBG39
 RESULT = 1500;        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expr ::= MINUS expr 
            {
              Integer RESULT =null;
		Location exleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.peek()).xleft;
		Location exright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.peek()).xright;
		Integer e = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		//@@CUPDBG40
 RESULT = -e;           
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expr ::= LPAREN expr RPAREN 
            {
              Integer RESULT =null;
		Location exleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).xleft;
		Location exright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).xright;
		Integer e = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		//@@CUPDBG41
 RESULT = e;           
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr ::= NUMBER 
            {
              Integer RESULT =null;
		Location nxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.peek()).xleft;
		Location nxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.peek()).xright;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		//@@CUPDBG42
 RESULT = n;           
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
