
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int BLACKONE = 12;
  public static final int BROWNONE = 15;
  public static final int DIVIDE = 8;
  public static final int REDONE = 18;
  public static final int ORANGEONE = 21;
  public static final int WHITETWO = 39;
  public static final int SQRT = 9;
  public static final int UMINUS = 5;
  public static final int BLUEONE = 30;
  public static final int BROWNTHREE = 17;
  public static final int GREENONE = 27;
  public static final int LPAREN = 7;
  public static final int SEMI = 2;
  public static final int MINUS = 4;
  public static final int RPAREN = 10;
  public static final int GRAYTWO = 37;
  public static final int GREENTHREE = 29;
  public static final int GOLDENTHREE = 42;
  public static final int BLACKTWO = 13;
  public static final int BROWNTWO = 16;
  public static final int PURPLETHREE = 35;
  public static final int REDTWO = 19;
  public static final int PURPLEONE = 33;
  public static final int ORANGETWO = 22;
  public static final int PLUS = 3;
  public static final int YELLOWTHREE = 26;
  public static final int EOF = 0;
  public static final int YELLOWONE = 24;
  public static final int BLUETWO = 31;
  public static final int EQUAL = 11;
  public static final int REDTHREE = 20;
  public static final int error = 1;
  public static final int GREENTWO = 28;
  public static final int NUMBER = 44;
  public static final int SILVERFOUR = 41;
  public static final int WHITEONE = 38;
  public static final int TIMES = 6;
  public static final int BLUETHREE = 32;
  public static final int GOLDENFOUR = 43;
  public static final int PURPLETWO = 34;
  public static final int SILVERTHREE = 40;
  public static final int YELLOWTWO = 25;
  public static final int BLACKTHREE = 14;
  public static final int GRAYONE = 36;
  public static final int ORANGETHREE = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "DIVIDE",
  "SQRT",
  "RPAREN",
  "EQUAL",
  "BLACKONE",
  "BLACKTWO",
  "BLACKTHREE",
  "BROWNONE",
  "BROWNTWO",
  "BROWNTHREE",
  "REDONE",
  "REDTWO",
  "REDTHREE",
  "ORANGEONE",
  "ORANGETWO",
  "ORANGETHREE",
  "YELLOWONE",
  "YELLOWTWO",
  "YELLOWTHREE",
  "GREENONE",
  "GREENTWO",
  "GREENTHREE",
  "BLUEONE",
  "BLUETWO",
  "BLUETHREE",
  "PURPLEONE",
  "PURPLETWO",
  "PURPLETHREE",
  "GRAYONE",
  "GRAYTWO",
  "WHITEONE",
  "WHITETWO",
  "SILVERTHREE",
  "SILVERFOUR",
  "GOLDENTHREE",
  "GOLDENFOUR",
  "NUMBER"
  };
}

